# Generated by Django 4.2.1 on 2023-05-31 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='date',
        ),
    ]
