# Generated by Django 4.2.1 on 2023-05-31 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0002_remove_exercise_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='athlete',
        ),
        migrations.AddField(
            model_name='workout',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
