# Generated by Django 4.2.1 on 2023-06-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_exercise_athlete_workout_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(max_length=100, verbose_name='Exercise Name'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rep',
            field=models.IntegerField(null=True, verbose_name='Rep'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='set',
            field=models.IntegerField(null=True, verbose_name='Set'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.FloatField(null=True, verbose_name='Weight'),
        ),
    ]
