# Generated by Django 4.2.1 on 2023-06-02 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_exercise_exercise_name_alter_exercise_rep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(blank=True, choices=[('Pull Ups', 'Pull Ups'), ('Dips', 'Dips'), ('Biceps', 'Biceps')], max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rep',
            field=models.IntegerField(default=0, verbose_name='Rep'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='set',
            field=models.IntegerField(default=0, verbose_name='Set'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Weight'),
        ),
        migrations.CreateModel(
            name='SeparateExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('separate_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='journal.exercise', verbose_name='Separate Exercise')),
            ],
        ),
    ]
