# Generated by Django 4.2.1 on 2023-06-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_exercise_exercise_name_alter_exercise_rep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='rep',
            field=models.IntegerField(verbose_name='Rep'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='set',
            field=models.IntegerField(verbose_name='Set'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.FloatField(verbose_name='Weight'),
        ),
        migrations.DeleteModel(
            name='SeparateExercise',
        ),
    ]
