# Generated by Django 4.2.1 on 2023-06-02 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_exercise_rep_alter_exercise_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='pic',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rep',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rep'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='set',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.CreateModel(
            name='ExerciseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exercise_images')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='journal.exercise')),
            ],
        ),
    ]
