# Generated by Django 4.2.1 on 2023-06-03 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_remove_exercise_pic_alter_exercise_rep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100, unique=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='exercise_pics', verbose_name='Pic')),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_name',
        ),
        migrations.DeleteModel(
            name='ExerciseImage',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_choice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='journal.exercisechoice', verbose_name='Exercise'),
        ),
    ]
