# Generated by Django 4.2.1 on 2023-06-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_exercisechoice_remove_exercise_exercise_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_choice',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(blank=True, choices=[('Pull Ups', 'Pull Ups'), ('Dips', 'Dips'), ('Biceps', 'Biceps')], max_length=100),
        ),
        migrations.AddField(
            model_name='exercise',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pics', verbose_name='Pic'),
        ),
        migrations.DeleteModel(
            name='ExerciseChoice',
        ),
    ]
