# Generated by Django 4.2.1 on 2023-06-05 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0009_remove_exercise_exercise_choice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='athlete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='custom_exercises',
            field=models.ManyToManyField(blank=True, related_name='custom_exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(blank=True, choices=[('Pull Ups', 'Pull Ups'), ('Dips', 'Dips'), ('Biceps', 'Biceps')], max_length=100, null=True),
        ),
    ]
